version: "3"

services:
    ide_core:
        image: codingminutes/ide_core
        env_file:
            - .env
        ports:
            - "8000:8000"
        build: .
        depends_on:
            - postgres
    postgres:
        image: postgres:12.7
        env_file:
            - .env