# Generated by Django 3.2.4 on 2021-08-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codefile',
            name='title',
            field=models.CharField(default='Untitled', max_length=256),
            preserve_default=False,
        ),
    ]
